mobile_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'left_wheel_joint'
  right_wheel: 'right_wheel_joint'
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  wheel_separation : 0.1
  wheel_radius : 0.03
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 10
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 10
servo_controller:
  type: "position_controllers/JointPositionController"
  joint: 'servo_joint'
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50